spring:
  application:
    name: selenum
#  profiles:
#    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    favicon:
      enabled: false
  http:
    multipart: 
      max-file-size: 50MB
      max-request-size: 55MB
  datasource:
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/choujiang?useSSL=false&serverTimezone=GMT
#      username: root
#      password: root
      url: jdbc:mysql://172.22.30.110:3306/choujiang?useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
      username: root
      password: root123
      # 初始化连接大小
      initialSize: 0
      # 连接池最大使用连接数量
      maxActive: 20
      # 连接池最小空闲
      minIdle: 0
      # 获取连接最大等待时间
      maxWait: 60000
      validationQuery: SELECT 1
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 25200000
      # 打开removeAbandoned功能
      removeAbandoned: true
      # 1800秒，也就是30分钟
      removeAbandonedTimeout: 1800
      # 关闭abanded连接时输出错误日志
      logAbandoned: true
      # 监控数据库
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*

server:
  port: 8080
  context-path: /
  compression:
    enabled: true
  session:
    timeout: 1000
  tomcat:
    uri-encoding: UTF-8

mybatis:
  configuration:
    # 缓存的全局开关
    cache-enabled: true
    # 延迟加载的全局开关
    lazy-loading-enabled: true
    # 等待数据库响应的秒数
    default-statement-timeout: 600
    # 开启自动驼峰命名规则映射
    map-underscore-to-camel-case: true
    # 当没有为参数提供特定的 JDBC 类型时，为空值指定 JDBC 类型
    # NULL VARCHAR OTHER
    jdbc-type-for-null: 'NULL'
    # 指定当结果集中值为 null 的时候是否调用映射对象的 setter（map 对象时为 put）方法
    call-setters-on-nulls: true
  mapper-locations: classpath:mapper/*Mapper.xml
    
